<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <RootNamespace>Scenic.Core</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="ScenicContext.fs" />
        <Compile Include="Components\ModelComponent.fs" />
        <Folder Include="Materials\" />
        <Folder Include="Scenes\Objects\" />
        <Compile Include="Workflows\Common\Keys.fs" />
        <Compile Include="Workflows\Standard\V1\Keys.fs" />
        <Compile Include="Workflows\Standard\V1\Impl.fs" />
        <Compile Include="Workflows\Impl.fs" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\CommonResourceFormats\src\CommonResourceFormats.AssetStore\CommonResourceFormats.AssetStore.fsproj" />
      <ProjectReference Include="..\..\..\CommonResourceFormats\src\CommonResourceFormats.GameDataFile\CommonResourceFormats.GameDataFile.fsproj" />
      <ProjectReference Include="..\..\..\CommonResourceFormats\src\CommonResourceFormats.ModelFile\CommonResourceFormats.ModelFile.fsproj" />
      <ProjectReference Include="..\..\..\CommonResourceFormats\src\CommonResourceFormats.PackFile\CommonResourceFormats.PackFile.fsproj" />
      <ProjectReference Include="..\..\..\FsToolbox\FsToolbox.GameDevelopment\FsToolbox.GameDevelopment.fsproj" />
      <ProjectReference Include="..\..\..\FsToolbox\FsToolbox.GLTF\FsToolbox.GLTF.fsproj" />
      <ProjectReference Include="..\..\..\FsToolbox\FsToolbox.OpenGL\FsToolbox.OpenGL.fsproj" />
    </ItemGroup>

</Project>
